import type { Metadata } from 'next';
import { dataset } from '@/src/lib/index-data';

export const metadata:Metadata={title:'API'};
const exact=[...dataset.slices].sort((a,b)=>b.resultCount-a.resultCount)[0].id;

const endpoints=[
  {key:'get-dataset-status',price:'Free',purpose:'Manifest, freshness, pinned source, counts and every exact slice ID.',input:'{}',output:'manifest · source · sliceIds · packageVersions'},
  {key:'preview-inference-chips',price:'Free',purpose:'Up to five verified rows for one optional exact slice.',input:`{"sliceId":"${exact}"}`,output:'slice · comparability · rows[0…5]'},
  {key:'rank-inference-chips',price:'$0.02',purpose:'Full exact-slice ranking with filters, grouping and bounded pagination.',input:`{"sliceId":"${exact}","metricView":"official","grouping":"best-per-accelerator","page":1,"pageSize":20}`,output:'slice · comparability · total · globally ranked rows'},
  {key:'compare-inference-chips',price:'$0.03',purpose:'Compare 2–8 accelerator slugs in one slice; deltas require an explicit baseline.',input:`{"sliceId":"${exact}","acceleratorSlugs":["amd-instinct-mi355x-amd-instinct-mi355x-288gb-hbm3e","nvidia-b300-nvidia-b300-sxm-270gb"],"baselineSlug":"amd-instinct-mi355x-amd-instinct-mi355x-288gb-hbm3e","metricView":"official"}`,output:'rows · missing-evidence reasons · baseline deltas'},
];

export default function ApiPage(){return <div className="shell page-space">
  <div className="page-intro"><span className="kicker">Lucid Agents API</span><h1>Evidence that machines can buy one question at a time.</h1><p>One server-only runtime owns discovery, validation, payment and execution. Next.js route modules delegate directly to its canonical handlers.</p></div>
  <section className="api-summary"><div><span className="kicker">Base path</span><code>/api/agent</code></div><div><span className="kicker">Payment rail</span><strong>x402 · Base Sepolia</strong></div><div><span className="kicker">Asset</span><strong>USDC</strong></div><div><span className="kicker">Response ceiling</span><strong>&lt; 1 MiB</strong></div></section>
  <section className="endpoint-list">{endpoints.map((e,i)=><article className="endpoint-card" key={e.key}><div className="endpoint-index">0{i+1}</div><div><div className="endpoint-title"><span className={e.price==='Free'?'free-price':'paid-price'}>{e.price}</span><h2>{e.key}</h2></div><p>{e.purpose}</p><h3>Request body</h3><pre><code>{`{"input":${e.input}}`}</code></pre><h3>Response data</h3><p className="response-shape">{e.output}</p><p className="route">POST /api/agent/entrypoints/{e.key}/invoke</p></div></article>)}</section>
  <section className="payment-flow"><div><span className="kicker">x402 flow</span><h2>Discover → challenge → settle → invoke</h2></div><ol><li><span>01</span><p>Read <a href="/api/agent/entrypoints">entrypoint discovery</a> or the <a href="/api/agent/.well-known/agent-card.json">agent card</a>.</p></li><li><span>02</span><p>Call a paid route without proof and receive an explicit 402 offer with exact price and network.</p></li><li><span>03</span><p>Settle USDC on Base Sepolia through the configured facilitator and repeat with the same idempotency key.</p></li><li><span>04</span><p>Lucid verifies payment before handler execution and returns a schema-validated result.</p></li></ol></section>
  <section className="state-gallery"><div className="section-head"><div><span className="kicker">Required service states</span><h2>Failure is a documented response, not an empty screen.</h2></div></div><div className="state-grid"><article className="state loading"><i/><strong>Loading</strong><p>Source-bound skeleton; controls remain labeled.</p></article><article className="state empty"><span>0</span><strong>No comparable results</strong><p>No incompatible fallback rows.</p></article><article className="state partial"><span>△</span><strong>Partial evidence</strong><p>Missing sources and reasons stay visible.</p></article><article className="state invalid"><span>!</span><strong>Invalid filters</strong><p>400 with field-level Zod issues.</p></article><article className="state payment"><span>402</span><strong>Payment required</strong><p>Exact x402 offer; never silently free.</p></article><article className="state error"><span>503</span><strong>API unavailable</strong><p>Retryable, idempotent, no phantom result.</p></article><article className="state success"><span>✓</span><strong>Paid success</strong><p>Receipt plus source hashes.</p></article><article className="state stale"><span>⏱</span><strong>Stale data</strong><p>Snapshot remains pinned, age explicit.</p></article></div></section>
  <section className="sdk-contract"><span className="kicker">Pinned runtime</span><div><code>@lucid-agents/core@5.0.0</code><code>@lucid-agents/http@4.0.0</code><code>@lucid-agents/payments@5.0.0</code></div><p>Without complete payment configuration, free endpoints boot and paid endpoints fail closed. They never execute as free operations.</p></section>
</div>}
