import type { Metadata } from 'next';
import manifest from '@/data/generated/manifest.json';
import coverage from '@/data/generated/coverage.json';
import quarantine from '@/data/generated/quarantine.json';
import changelog from '@/data/generated/changelog.json';

type QuarantineRow={path:string;reason:string;detail:string};

export const metadata:Metadata={title:'Updates'};

export default function UpdatesPage(){const quarantineRows=quarantine as QuarantineRow[];return <div className="shell page-space">
  <div className="page-intro"><span className="kicker">Dataset updates</span><h1>A snapshot should explain exactly how it changed.</h1><p>V1 is fixed to one reviewed source commit. Promotion is atomic: importer, schemas, provenance, coverage and deterministic hashes must all pass first.</p></div>
  <section className="manifest-grid"><div><span>Release</span><strong>{manifest.release}</strong></div><div><span>Division</span><strong>{manifest.division}</strong></div><div><span>Results</span><strong>{manifest.recordCount}</strong></div><div><span>Systems</span><strong>{manifest.systemCount}</strong></div><div><span>Accelerators</span><strong>{manifest.acceleratorCount}</strong></div><div><span>Quarantined</span><strong>{manifest.quarantineCount}</strong></div></section>
  <section className="update-block"><div className="block-head"><div><span className="kicker">Manifest</span><h2>Immutable source boundary</h2></div><span className="live-badge">PINNED</span></div><dl className="manifest-lines"><div><dt>Repository</dt><dd><a href="https://github.com/mlcommons/inference_results_v6.0" target="_blank" rel="noreferrer">mlcommons/inference_results_v6.0 ↗</a></dd></div><div><dt>Commit</dt><dd><code>{manifest.sourceCommit}</code></dd></div><div><dt>Snapshot SHA-256</dt><dd><code>{manifest.snapshotSha256}</code></dd></div><div><dt>Last reviewed</dt><dd>{manifest.reviewedAt}</dd></div><div><dt>Freshness</dt><dd>{manifest.freshness}; no live scraping</dd></div></dl></section>
  <section className="update-block"><div className="block-head"><div><span className="kicker">Coverage matrix</span><h2>What the source can actually support</h2></div></div><div className="table-wrap"><table><thead><tr><th>Workload</th><th>Scenario</th><th>Accepted</th><th>Vendors</th><th>Families</th></tr></thead><tbody>{coverage.map(row=><tr key={`${row.workload}-${row.scenario}`}><td><strong>{row.workload}</strong></td><td>{row.scenario}</td><td>{row.accepted}</td><td>{row.vendors.join(', ')||'None'}</td><td><small>{row.families.join(', ')||'No valid evidence'}</small></td></tr>)}</tbody></table></div></section>
  <section className="two-col-updates"><article className="update-block"><div className="block-head"><div><span className="kicker">Quarantine</span><h2>{quarantineRows.length?`${quarantineRows.length} records excluded`:'No records excluded'}</h2></div></div>{quarantineRows.length?<ul>{quarantineRows.map(row=><li key={row.path}><strong>{row.reason}</strong><code>{row.path}</code><p>{row.detail}</p></li>)}</ul>:<p>All 145 allowlisted base performance summaries passed the current reviewed registry and validity rules. The negative fixture still proves ambiguous identities and counts are rejected.</p>}</article><article className="update-block"><div className="block-head"><div><span className="kicker">Changelog</span><h2>Snapshot history</h2></div></div>{changelog.map(row=><div className="change" key={row.version}><span>{row.generatedAt}</span><strong>Initial import · +{row.added}</strong><p>{row.note}</p><code>{row.version}</code></div>)}</article></section>
  <section className="runbook"><div><span className="kicker">Manual update and rollback</span><h2>Review is a deliberate operation.</h2></div><div><pre><code>{`# Update candidate\ngit -C ../mlperf-inference-v6 fetch origin\n# edit the pinned commit only after review\nnpm run data:fixture\nnpm run data:full\nnpm run data:verify\nnpm test && npm run build\n\n# Rollback\ngit revert <dataset-promotion-commit>\nnpm run data:verify\nnpm run build`}</code></pre></div></section>
</div>}
