import type { Metadata } from 'next';
import Link from 'next/link';
import { dataset } from '@/src/lib/index-data';

export const metadata: Metadata={title:'Methodology'};

const dimensions=[['Release','MLPerf Inference v6.0 only'],['Division','Closed only'],['Workload','llama3.1-8b, gpt-oss-120b, or deepseek-r1'],['Scenario','Offline, Server, or Interactive'],['Accuracy','Official-default evidence; TEST07/TEST09 variants excluded from V1'],['Metric','Official submitted-system tokens per second'],['Unit','tokens/s; higher is better']];

export default function Methodology(){return <div className="shell page-space article-page">
  <div className="page-intro"><span className="kicker">Methodology</span><h1>Fast only means something inside a defined slice.</h1><p>Inference Chip Index normalizes official submission evidence without collapsing unlike workloads, scenarios or systems into a context-free score.</p></div>
  <section className="method-callout"><div><span className="giant-num">07</span><p>dimensions must match before two results share a ranking.</p></div><div>{dimensions.map(([a,b])=><dl key={a}><dt>{a}</dt><dd>{b}</dd></dl>)}</div></section>
  <section className="prose-grid"><div><span className="section-number">01</span><h2>Systems are primary</h2></div><div><p>MLPerf publishes results for submitted systems. The primary metric displayed here is that official system result. It reflects the submitted topology, software and accelerator count—not a universal property of a chip.</p><p>The index may show a clearly labeled per-accelerator value only when both <code>accelerators_per_node</code> and <code>number_of_nodes</code> are explicit positive integers in the pinned system JSON. It divides official tokens/s by their product. It never infers a count from strings such as <code>x8</code> or <code>NVL72</code>.</p></div></section>
  <section className="prose-grid"><div><span className="section-number">02</span><h2>Stable identity, immutable versions</h2></div><div><p>An accelerator, submitted system and benchmark result are separate entities. A logical result ID remains stable for the same exact slice and system. A content-version ID changes when normalized content changes.</p><p>Every record carries repository, commit, path, immutable GitHub URL and SHA-256. The dataset manifest hashes the ordered accelerators, systems, results and slices, so an auditor can detect any altered snapshot.</p></div></section>
  <section className="prose-grid"><div><span className="section-number">03</span><h2>Validity before rank</h2></div><div><p>V1 admits only base <code>performance/run_1/mlperf_log_summary.txt</code> records whose summary states <code>Result is : VALID</code> and contains a recognized positive throughput metric. TEST07 and TEST09 branches are not mixed with official-default rows.</p><p>Identity and family names come from a reviewed alias registry applied to the accelerator model declared in the system JSON. Missing system evidence, unreviewed identity, ambiguous counts, invalid summaries, scenario conflicts, unknown units and parser failures enter the quarantine report.</p></div></section>
  <section className="prose-grid"><div><span className="section-number">04</span><h2>Ranking and ties</h2></div><div><p>Tokens per second is higher-is-better. Rows are sorted by the selected metric, then by stable result ID. Equal numeric values receive the same rank, and the next position skips accordingly. Ranking occurs across the full filtered set before pagination.</p><p><strong>Best per accelerator</strong> retains the best submitted system for each exact accelerator identity. <strong>All systems</strong> keeps every qualifying submission. Derived per-accelerator values are never selected by default.</p></div></section>
  <section className="prose-grid"><div><span className="section-number">05</span><h2>Interactive convention</h2></div><div><p>Some official paths classify a result as Interactive while the LoadGen summary reports Server. The importer preserves the official path scenario and accepts this specific observed convention; any other path/summary mismatch is quarantined. The raw summary remains linked beside the row.</p><p>This is a normalization decision, not a claim that Interactive and Server are interchangeable. They remain separate slices.</p></div></section>
  <section className="limit-card"><span className="kicker">Limits</span><h2>What this index does not claim</h2><ul><li>No accelerator is universally fastest.</li><li>Benchmark throughput is not cost, latency, energy, availability or workload-quality advice.</li><li>Derived values do not recreate an official one-accelerator submission.</li><li>The fixed snapshot does not include later corrections unless a new reviewed version is promoted.</li><li>Vendor and submitter names are evidence fields, not endorsements.</li></ul></section>
  <section className="source-panel"><div><span className="kicker">Reproducibility</span><h2>One command rebuilds the source snapshot.</h2><code>npm run data:full &amp;&amp; npm run data:verify</code></div><div><p>Source commit</p><code>{dataset.manifest.sourceCommit}</code><p>Snapshot</p><code>{dataset.manifest.snapshotSha256}</code><Link href="/updates">Inspect coverage and changelog →</Link></div></section>
</div>}
